### ISSUE TITLE
Tooltips Hidden by Formatting Toolbar

### ISSUE THREAD

**Issue by irmerk** [accordproject/web-components#87]
# Bug Report 🐛
Tooltips for conditional variables and clause template action icons (test, edit, delete) are hidden behind the formatting toolbar

## Expected Behavior
Tooltips should be above everything else

## Current Behavior
<img width="652" alt="Screen Shot 2020-05-15 at 10 06 36 AM" src="https://user-images.githubusercontent.com/36460856/82060314-357e8900-9695-11ea-9c9d-2becfd909397.png">

## Possible Solution
Raise the `z-index` of these components

## Steps to Reproduce
1. View the [demo](https://ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor)
2. Place cursor after the clause template, create new lines until sufficient scrolling
3. Scroll to make the action icons just below the formatting toolbar
4. Hover and see them hidden under the toolbar

### Desktop
 - OS: macOS
 - Browser: Chrome
 - Version: `0.91.0`

**Comment by irmerk** [comment]
Also seen in this reproduction is the formatting toolbar width issue?

**Comment by arteevraina** [comment]
@irmerk Can I take a look at this?

**Comment by shubhamkakkar** [comment]
@irmerk I am planning to look into this.
1. the demo link you addded in the description doesnt works
2. can you guide me to the exact component, I am new to the projec so dont have much idea;

**Comment by irmerk** [comment]
Sorry about that @shubhamkakkar I updated the demo link - it was before we moved back to Netlify. Yes so these tooltips are located [here in the Clause component](https://github.com/accordproject/web-components/blob/master/packages/ui-contract-editor/src/lib/components/Clause/index.js#L178-L237), that should be your starting point.

**Comment by dselman** [comment]
@DianaLease is this now fixed with the z-index changes?

**Comment by irmerk** [comment]
I believe the changes we mentioned during the Working Group call were in relation to the buttons on a clause, not the formatting toolbar.

**Comment by DianaLease** [comment]
@dselman @irmerk It's still an issue, but not as bad as the screenshot in the original post as we have changed the toolbar since then. Here's an updated screenshot:
![Screen Shot 2021-02-11 at 3 46 47 PM](https://user-images.githubusercontent.com/20543103/107696869-7afdd000-6c80-11eb-96c0-111e1b61dd36.png)

**Comment by Udbhavbisarya23** [comment]
@DianaLease @irmerk @dselman If this is still an issue, can i be assigned to this?

**Comment by Udbhavbisarya23** [comment]
The z-index of the tooltip is 99 and that of the toolbar is 10.
I believe this issue can be fixed by removing the z-index of the formatting toolbar or by adding a position and z-index property to the text editor.

**Comment by irmerk** [comment]
Hmm, unsure why the toolbar would need an index, I don't think it will need to be on top of anything else.
